= Testing Java Projects
:page-aliases: Testing_Java_Projects.adoc
:language: Java
:language-small: java

This page will discuss common topics around working with test suites using the Mill build tool

== Basic Testing Configuration

include::partial$example/javalib/testing/1-testing.adoc[]

=== Common Test Framework Support

include::partial$example/javalib/testing/2-test-suite.adoc[]

=== Test Dependencies

include::partial$example/javalib/testing/3-test-deps.adoc[]

== Programmable Testing Configuration

=== Test Parallelism

include::partial$example/javalib/testing/5-test-parallel.adoc[]

=== Test Grouping

include::partial$example/javalib/testing/6-test-grouping.adoc[]

=== Test Grouping & Test Parallelism together

include::partial$example/javalib/testing/7-test-group-parallel.adoc[]

=== Batch Mode for Test Frameworks

Some sbt-testing-interface frameworks use `Runner.tasks` to wire relationships between related
test tasks, and need to see the full batch of selected tasks at once rather than having Mill
pre-filter and parallelize them. For example, https://disneystreaming.github.io/weaver-test/[Weaver]'s
`GlobalResource` setup is connected to suites from the full task batch.

For such frameworks, override `testBatchFrameworkTasks` to `true`:

[source,scala]
----
object test extends ScalaTests {
  def testBatchFrameworkTasks = true
}
----

When enabled, Mill passes each fork group's full set of selected tasks to the framework in a
single forked JVM. This disables intra-group queue parallelism (all classes in a
xref:#_test_grouping[`testForkGrouping`] group run in one subprocess), though separate fork
groups still run independently.
