# action.yml

runs:
  using: "composite"
  steps:
    - name: Debug
      run: |
        echo "old ANDROID_HOME:"
        tree $ANDROID_HOME -L 2 -d || true
        echo "old ANDROID_SDK_ROOT:"
        tree $ANDROID_SDK_ROOT -L 2 -d || true
        tree $HOME/.android -L 2 || true
        ps aux | grep adb
        pwd
        ls -lah
      shell: bash

    - name: Set ANDROID_HOME
      run: echo "ANDROID_HOME=$HOME/.android/sdk" >> $GITHUB_ENV
      shell: bash

    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash

    - name: Cleanup any previous avd's to avoid signing key conflicts
      run: rm -rf /home/runner/.android/avd
      shell: bash
