# Uncommment this to replace the rest of the file when you want to debug stuff in CI


#name: Run Debug
#
#on:
#  push:
#  pull_request:
#  workflow_dispatch:
#
#jobs:
#  debug:
#    runs-on: ubuntu-latest
##    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v4
#        with: { fetch-depth: 1 }
#
#      - run: "echo temurin:11 > .mill-jvm-version"
#
#      - uses: sbt/setup-sbt@v1
#
#
#      - run:  ./mill 'integration.migrating[init].local.daemon.testOnly' mill.integration.MillInitSbtGatlingTests
#



# We run full CI on push builds to main and on all pull requests
#
# To maximize bug-catching changes while keeping CI times reasonable, we run
# tests scattered between Java 11/17/24, across linux/mac/windows, intel/arm


name: Run Tests

on:
  push:
    branches-ignore:
      - '**-patch-**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

# cancel older runs of a pull request;
# this will not cancel anything for normal git pushes
concurrency:
  # * For runs on other repos, always use the `ref_name` so each branch only can have one concurrent run
  # * For runs on `com-lihaoyi/mill`, use `head_ref` to allow one concurrent run per PR, but `run_id` to
  #   allow multiple concurrent runs in master
  group: cancel-old-pr-runs-${{ github.workflow }}-${{ (github.repository != 'com-lihaoyi/mill' && github.ref_name) || (github.head_ref || github.run_id) }}
  cancel-in-progress: true

jobs:
  # Jobs are listed in rough order of priority: if multiple jobs fail, the first job
  # in the list should be the one that's most worth looking into
  build-linux:
    if: (github.event.action == 'ready_for_review') || (github.event.pull_request.draft == false)
    uses: ./.github/workflows/pre-build.yml
    with:
      os: ubuntu-latest
      shell: bash

  test-docs:
    if: (github.event.action == 'ready_for_review') || (github.event.pull_request.draft == false)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - run: ./mill -i website.fastPages + website.checkBrokenLinks


  linux:
    needs: build-linux
    strategy:
      fail-fast: false
      matrix:

        include:
          # For most tests, run them arbitrarily on Java 11 or Java 17 on Linux, and
          # on the opposite version on Windows below, so we get decent coverage of
          # each test on each Java version and each operating system
          # We also try to group tests together to manually balance out the runtimes of each jobs

          - java-version: 17
            millargs: "'example.androidlib.__.local.daemon'"
            install-android-sdk: true


    uses: ./.github/workflows/post-build-selective.yml
    with:
      install-android-sdk: ${{ matrix.install-android-sdk || false }}
      install-sbt: ${{ matrix.install-sbt || false }}
      install-xvfb: ${{ matrix.install-xvfb || false }}
      java-version: ${{ matrix.java-version }}
      millargs: ${{ matrix.millargs }}
      shell: bash

