name: Scheduled Migration Tests

on:
  schedule:
    # 04:00 every Sunday
    - cron: '0 4 * * 0'
  workflow_dispatch:
  push:

concurrency:
  group: scheduled-migration-tests
  cancel-in-progress: true

env:
  FORCE_COLOR: '1'
  MILL_TEST_SCHEDULED: 'true'
  MILL_TEST_TIMEOUT_MINUTES: '60'

jobs:

  build-windows:
    uses: ./.github/workflows/pre-build.yml
    with:
      java-version: 25
      os: windows-latest
      shell: powershell


  windows:
    needs: build-windows
    uses: ./.github/workflows/post-build-selective.yml
    with:
      os: windows-latest
      java-version: 25
      millargs: "example.migrating._._.testForked"
      extra: "--jobs=1"
      mill-test-scheduled: 'true'
      mill-test-timeout-minutes: '60'
      shell: powershell

